name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Copy files to target directory
      run: |
        sudo cp -r backend/* /home/lch/python/backend/

    - name: Install Dependencies
      working-directory: /home/lch/python/backend/
      run: |
        source /home/lch/python/backend/.venv/bin/activate
        cd /home/lch/python/backend
        poetry install --no-root

    - name: Execute start script
      run: |
        cd /home/lch/python/backend
        ./stop.sh
        ./start.sh