name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build and Deploy
      working-directory: ./frontend
      run: |
        npm install
        npm run build
        sudo cp -r dist/* /var/www/front/